# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _                 
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  ) 
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                                                 /____/        
#
# Title of your website
title: "Feeling Responsive"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "A Responsive Theme for Jekyll"


# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "»Feeling Responsive« is a responsive theme for Jekyll based on the fabulous foundation framework with beautiful typography and a bright color palette."


# This is a switch to easily change the {{ site.url }}-variable to develop the theme locally
url: "http://localhost:4000"
# - url: "http://phlow.github.io/feeling-responsive"
baseurl: ""


# Logo size is 600x80 pixels
logo: "logo.png"


# Paginates all X entries
paginate: 5


# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: pygments
exclude: []
include: ['.htaccess']


# The language setting is used in /includes/header.html for html-settings
language: "en"




#       _   __            _             __  _           
#      / | / /___ __   __(_)___ _____ _/ /_(_)___  ____ 
#     /  |/ / __ `/ | / / / __ `/ __ `/ __/ / __ \/ __ \
#    / /|  / /_/ /| |/ / / /_/ / /_/ / /_/ / /_/ / / / /
#   /_/ |_/\__,_/ |___/_/\__, /\__,_/\__/_/\____/_/ /_/ 
#                       /____/                          
#
#  Open _data/navigation.yml to adjust the left and right topbar navigation
#



#     _____ __________ 
#    / ___// ____/ __ \
#    \__ \/ __/ / / / /
#   ___/ / /___/ /_/ / 
#  /____/_____/\____/    Verify Website to Webmaster Tools

google_author:             "https://plus.google.com/u/0/118311555303973066167"
google_site_verification:  "Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ"
bing_webmastertools_id:    "0FB4C028ABCF07C908C54386ABD2D97F"
# alexa_verify_id:         ""



#       ______            _                      
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  ) 
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicons, Apple Touch Buttons
#                                                 More information » http://j.mp/apple-touch-icons

favicon:                         "/images/favicon-32x.png"                    # iOS7 Size 32x32
apple_touch_icon_iphone:         "/images/touch-icon-iphone-60x.png"          # iOS7 Size 60x60
apple_touch_icon_iphone_retina:  "/images/touch-icon-iphone-retina-120x.png"  # iOS7 Size 120x120
apple_touch_icon_ipad:           "/images/touch-icon-ipad-76x.png"            # iOS7 Size 76x76
apple_touch_icon_ipad_retina:    "/images/touch-icon-ipad-retina-152x.png"    # iOS7 Size 152x152
apple_touch_icon_precomposed:    "/images/touch-icon-android-152x.png"        # iOS7 Size 152x152


#       ______                __                __  
#      / ____/___ _________  / /_  ____  ____  / /__
#     / /_  / __ `/ ___/ _ \/ __ \/ __ \/ __ \/ //_/
#    / __/ / /_/ / /__/  __/ /_/ / /_/ / /_/ / ,<   
#   /_/    \__,_/\___/\___/_.___/\____/\____/_/|_|      Facebook-Optimization › http://j.mp/fb_optimize

og_image:                           "http://images.phlow.de/phlow/phlow_de-logo-512x.png"
og_locale:                          "en_EN"
og_type:                            "website"
og_title:                           "Feeling Responsive – A Responsive Theme for Jekyll"
og_description:                     "Feeling Responsive is built on the fabulous Foundation Framework and comes with lots of features to show your content right."
# og_url:                           ""
# og_site_name:                     ""


#      _____            _       __   __  ___         ___      
#     / ___/____  _____(_)___ _/ /  /  |/  /__  ____/ (_)___ _
#     \__ \/ __ \/ ___/ / __ `/ /  / /|_/ / _ \/ __  / / __ `/
#    ___/ / /_/ / /__/ / /_/ / /  / /  / /  __/ /_/ / / /_/ / 
#   /____/\____/\___/_/\__,_/_/  /_/  /_/\___/\__,_/_/\__,_/  
#
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation
#

